//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.23 at 07:46:08 PM CEST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://todos.be/soap/todos", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package be.ucll.examen.SOAP.models.v1;
