//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.06.23 at 07:46:08 PM CEST 
//


package be.ucll.examen.SOAP.models.v1;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Todo complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Todo"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="comment" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="creation_date" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="due_date" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="todo_status" type="{http://todos.be/soap/todos}todo_status"/&gt;
 *         &lt;element name="todo_for" type="{http://todos.be/soap/todos}todo_for"/&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/&gt;
 *         &lt;element name="user" type="{http://todos.be/soap/todos}user"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Todo", propOrder = {
    "title",
    "comment",
    "creationDate",
    "dueDate",
    "todoStatus",
    "todoFor",
    "id",
    "user"
})
public class Todo {

    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String comment;
    @XmlElement(name = "creation_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar creationDate;
    @XmlElement(name = "due_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dueDate;
    @XmlElement(name = "todo_status", required = true)
    @XmlSchemaType(name = "string")
    protected TodoStatus todoStatus;
    @XmlElement(name = "todo_for", required = true)
    @XmlSchemaType(name = "string")
    protected TodoFor todoFor;
    protected long id;
    @XmlElement(required = true)
    protected User user;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCreationDate(XMLGregorianCalendar value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the dueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDueDate() {
        return dueDate;
    }

    /**
     * Sets the value of the dueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDueDate(XMLGregorianCalendar value) {
        this.dueDate = value;
    }

    /**
     * Gets the value of the todoStatus property.
     * 
     * @return
     *     possible object is
     *     {@link TodoStatus }
     *     
     */
    public TodoStatus getTodoStatus() {
        return todoStatus;
    }

    /**
     * Sets the value of the todoStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link TodoStatus }
     *     
     */
    public void setTodoStatus(TodoStatus value) {
        this.todoStatus = value;
    }

    /**
     * Gets the value of the todoFor property.
     * 
     * @return
     *     possible object is
     *     {@link TodoFor }
     *     
     */
    public TodoFor getTodoFor() {
        return todoFor;
    }

    /**
     * Sets the value of the todoFor property.
     * 
     * @param value
     *     allowed object is
     *     {@link TodoFor }
     *     
     */
    public void setTodoFor(TodoFor value) {
        this.todoFor = value;
    }

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

    /**
     * Gets the value of the user property.
     * 
     * @return
     *     possible object is
     *     {@link User }
     *     
     */
    public User getUser() {
        return user;
    }

    /**
     * Sets the value of the user property.
     * 
     * @param value
     *     allowed object is
     *     {@link User }
     *     
     */
    public void setUser(User value) {
        this.user = value;
    }

}
